name = "Waluigi"
uuid = "aa5a021a-6c35-4f46-b189-2143d43923dc"
authors = ["Micah Rufsvold <mrufsvold@mathematica-mpr.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
